spring.application.name=email-writer-sb
gemini.api.key=${GEMINI_KEY}
gemini.api.url=${GEMINI_URL}
#//axious dependency in vscode for fetching api
#material dependency ui for front end
server.port=${PORT:8080}